name: Publish resume in JSONResume format as Github Page

on:
  push:
    branches:
      - main

jobs:
  check_run:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build:
    runs-on: ubuntu-latest
    needs: check_run
    steps:
      - uses: actions/checkout@v3
      - name: Export resume as HTML
        run: |
          npm update -g npm --no-fund
          npm install resumed -g --no-fund
          npm install jsonresume-theme-rocketspacer -g --no-fund
          resumed validate resume.jsonc
          resumed render resume.jsonc --theme jsonresume-theme-rocketspacer --output index.html
      - name: Commit published HTML
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -n "$(git status --porcelain ./index.html)" ]; then
            git add ./index.html
            git commit -m "[ci skip] chore(docs/index.html): update resume page"
            echo ::set-output name=exit_code::0
          else
            echo ::set-output name=exit_code::1
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: steps.commit.outputs.exit_code == 0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
